---
spring:
  application:
    name: reservation-service
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgres://kbjlrqic:jg0vLGmuQ27kAp_BwvgK422x9o3G48bh@stampy.db.elephantsql.com:5432/kbjlrqic
    username: kbjlrqic
    password: '{cipher}3451b6c9ce5bd91082afc85b681eef108131ba87e6c5aacc2c4e1ce516ba320b63c2aacc0319af8ff528ceee8fa03f60c6dd2cf912dbbbb8978126469af58152'
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: create


management:
  endpoints:
    web:
      exposure:
        include: *
  security:
    enabled: false
security:
  basic:
    enabled: false
    
eureka:
  client:
    serviceUrl:
      defaultZone: https://p-service-registry-339760a6-b634-40b1-bb42-0f1699a2aaf0:RfR9XJuLBCsz@eureka-ce7e8bcd-06c6-4cc8-93ab-b87b78bb0d57.cfapps.io/eureka
