---
spring:
  application:
    name: reservation-service
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgres://kbjlrqic:jg0vLGmuQ27kAp_BwvgK422x9o3G48bh@stampy.db.elephantsql.com:5432/kbjlrqic
    username: kbjlrqic
    password: '{cipher}3451b6c9ce5bd91082afc85b681eef108131ba87e6c5aacc2c4e1ce516ba320b63c2aacc0319af8ff528ceee8fa03f60c6dd2cf912dbbbb8978126469af58152'
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: create
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  cache:
    type: redis
  redis:
    host: redis-13519.c16.us-east-1-2.ec2.cloud.redislabs.com
    port: 13519
  rabbitmq:
    host: baboon.rmq.cloudamqp.com
    port: 5672
    username: awiymfbp
    password: wBVmFlXLDtOtMgIWZk4qHftJKT1QPVGV

custom:
  featureSwitch:
    userApiEnabled: false
    

security:
  basic:
    enabled: false
management:
  security:
    enabled: false
