---
spring:
  application:
    name: user-service
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgres://kbjlrqic:jg0vLGmuQ27kAp_BwvgK422x9o3G48bh@stampy.db.elephantsql.com:5432/kbjlrqic
    username: kbjlrqic
    password: '{cipher}AgB3mqwn1958q1rZZag0zNx5C13hwdjmrUyghzYctdh+wuN2dRjgTcF6h1k2BrpVj1yIM0RIu/zofn4wRbunKmlDlREo1glEfxqDU4xruJTf9v6v8RjU87L7+amJWGsMY1MNcl4WfPVjkQBWIcMXzoECZXRk8eLQsu9gxTy06VaL6t0UB435W3DpdwHAuvc1Qp9hhi/vuOWiYhM3otOukJ/Z4mvyU2J/w6Fv2/sRqShT8SdwZqtG87FvpuCtAPy7+1iA+RkNyDlpX8sLN4C4CO4/e3CwV+s4AVUCdQoq6h51u860uflqEfZZlb4cgjMjbgh1tiII/f3GgECI6nko+kJSeLClwXebRuhJgyKBricaPrkqOwgTiTstjJyi51Mh6D0e57u02IXdPNYT7TGLsdDlPxqV8s8PPhy5YBIq+wyEFNIn39jC0VDBCoXjzbL4cjr+WiMpBx3MMWaAWnVFM4kWzOtscD0coOS7GelfN2Dxrp0yz7lU+vjrandVip9Xgxz8vjkVKfJ6TY1SAWLNt3Gl3puw4P1c6qSIeKixCnls21ncVMkf/x9kJAnIOuN1NPH7SPzsvlXyP31QN77JnuZQTSvU1DiAt0iZHH5XUj2mHBXy3D1+z5Y583PHdGSyeEeqVGkksnZ6Yz14H71q03Gs7GxZapp7YezoiYebE29ErgP+JAhQnr69Ih8qohPkZAdVMMe3r/+7IfLbLhTwo8/GVneGdAAEq6+zNXQ9sdHwtgIfLCfwRwvNf0eZWxfw2R0='
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: create
app:
  users:
    key: '{cipher}AgAdu8g0jlK8vKKQer3oCPjxXM1o7/VXwwZ4/CpAdrVZUiyg5bteKOWzDQmmHmL7R9cmB5HiFVDs2pVr3RLiODcUaL6YapaEly6ryR9YRFAX0jy6jPH/O4S2QuiA73ysPvf9arG5SKG48KxyIo1Ia/pK7R3z2cTASexEWRxBIt61R4/Zpa2VX9HF7m4LCKbdoXbSgmNJIoPXjyjEdnTbA7jvPkP2ypvrsbj9Nex8YapYzvfvECr5Q6YBPPgUNmKuz0hvdaNVf+htQEz6QqnpYJY/U23g2VjmidBtWLuEwcnzIV1nJd3IN4ihcmuUL47l9/oaQogg2i8ZozriXQ8+Pog/c+bNvO2jgaBL1QIGx4ImAblxBdLr35WfVvEdyQ0ST5nh0bhmow/CD+txFSSJVJ/T3iOxrKuUMhEDie4giyYReNzLEKz8Vj8uy9HmHiD2cyB9e1jjAkvTSIhiuF5fj+aBT3/wM2oMF1n5wKYuKK7hAqarEfCTbEjFWATCyEiDyksfvs4keOk/nSKyw1aF/F6iQpxqq+U2WWfqg/t1YIBd/51Cq+MyVYRoo6raXThPmZmCEbrkONcq89WqwVijkIX+S4AQqfnYt+uIMWqT9jipGCySuFmxEPWYGv5qEgzNwm0pP0ZAdwp+Iusmpp/EFAkbun2yaRz1Hs9TG15Q6D/vbwczzwJPPaMxSRPGF6UqsANlJsL2d1DoIz/p/W9hk40u'
