---
spring:
  application:
    name: user-service
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgres://kbjlrqic:jg0vLGmuQ27kAp_BwvgK422x9o3G48bh@stampy.db.elephantsql.com:5432/kbjlrqic
    username: kbjlrqic
    password: '{cipher}407d8598532b6676b29919a329c8e4873da3c12fa3f407fee55edf1647ec1275f8bdb3397f2e906a08c5b87eee2e5e9bb646eb0238af2f7573016088abc2ce39'
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: create
mavs:
  users:
    key: '{cipher}48ebc4b028f6eaf29dcba067e932ce246e8a0cea0de6cd728a85b97ad4cd7f7d'
