---
spring:
  application:
    name: gateway-service-service
  profiles: local
server:
  port: 7070
eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    user-service:
      path: /user-service/**
      sensitive-headers: Set-Cookie,Authorization
    reservation-service:
      path: /reservation-service/**
      sensitive-headers: Set-Cookie,Authorization
    eureka:
      path: /eureka/**
      sensitive-headers: Set-Cookie,Authorization
      url: http://localhost:8761
    auth-service:
      path: /auth/**
      service-id: AUTH-SERVICE
      # By default, all requests to gallery service for example will start with: "/gallery/"
      # What will be sent to the gallery service is what comes after the path defined, 
      # So, if request is "/gallery/view/1", gallery service will get "/view/1".
      # In case of auth, we need to pass the "/auth/" in the path to auth service. So, set strip-prefix to false
      strip-prefix: false
      sensitive-headers: Cookie,Set-Cookie # Exclude authorization from sensitive headers
      
hystrix:
  command:
    user-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
    reservation-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
    eureka:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
